# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Sanjay Seetharaman"
email: 'sanjayms0111@gmail.com'
description: "My personal homepage"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://chiefsan.github.io" # the base hostname & protocol for your site, e.g. https://example.com
github_username: 'chiefsan'
linkedin_username: 'sanjayseetharaman'
home_section_title: 'Projects'
home_section_subtitle: 'Projects'

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
### Phantom settings
paginate: 10
footer_text: '© 2020 Sanjay Seetharaman'
admin_name: 'Sanjay Seetharaman'
google_analytics: "UA-164910723-1" # Update with your own tracking ID
enable_contact: false

#### Phantom Navigation menu
enable_nav: true
nav_item:
  - { url: '/', text: 'Home' }
  - { url: '/cv', text: 'CV' }

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html:
  clippings: all
  ignore:
    envs: development

theme_skin: ceramic

sass:
  style: compressed